/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CoronaChart {
    }
    interface GithubCard {
        "avatar": string;
        "followersCount": number;
        "gistsCount": number;
        "name": string;
        "repoCount": number;
        "username": string;
    }
    interface SearchBar {
    }
    interface UsersList {
    }
}
declare global {
    interface HTMLCoronaChartElement extends Components.CoronaChart, HTMLStencilElement {
    }
    var HTMLCoronaChartElement: {
        prototype: HTMLCoronaChartElement;
        new (): HTMLCoronaChartElement;
    };
    interface HTMLGithubCardElement extends Components.GithubCard, HTMLStencilElement {
    }
    var HTMLGithubCardElement: {
        prototype: HTMLGithubCardElement;
        new (): HTMLGithubCardElement;
    };
    interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {
    }
    var HTMLSearchBarElement: {
        prototype: HTMLSearchBarElement;
        new (): HTMLSearchBarElement;
    };
    interface HTMLUsersListElement extends Components.UsersList, HTMLStencilElement {
    }
    var HTMLUsersListElement: {
        prototype: HTMLUsersListElement;
        new (): HTMLUsersListElement;
    };
    interface HTMLElementTagNameMap {
        "corona-chart": HTMLCoronaChartElement;
        "github-card": HTMLGithubCardElement;
        "search-bar": HTMLSearchBarElement;
        "users-list": HTMLUsersListElement;
    }
}
declare namespace LocalJSX {
    interface CoronaChart {
    }
    interface GithubCard {
        "avatar"?: string;
        "followersCount"?: number;
        "gistsCount"?: number;
        "name"?: string;
        "repoCount"?: number;
        "username"?: string;
    }
    interface SearchBar {
        "onSearch"?: (event: CustomEvent<string>) => void;
    }
    interface UsersList {
    }
    interface IntrinsicElements {
        "corona-chart": CoronaChart;
        "github-card": GithubCard;
        "search-bar": SearchBar;
        "users-list": UsersList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "corona-chart": LocalJSX.CoronaChart & JSXBase.HTMLAttributes<HTMLCoronaChartElement>;
            "github-card": LocalJSX.GithubCard & JSXBase.HTMLAttributes<HTMLGithubCardElement>;
            "search-bar": LocalJSX.SearchBar & JSXBase.HTMLAttributes<HTMLSearchBarElement>;
            "users-list": LocalJSX.UsersList & JSXBase.HTMLAttributes<HTMLUsersListElement>;
        }
    }
}
